name: 'Update Steam box'

on:
  push:
    paths:
      - 'boxes/steam'
  schedule:
    - cron: "0 * * * *"

defaults:
  run:
    working-directory: ./boxes/steam

jobs:
  update:
    runs-on: ubuntu-latest
    environment: steam
    env:
      STEAM_OPTION: 'RECENT'
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: ${{ vars.GIST_ID }}
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      STEAM_ID: ${{ secrets.STEAM_ID }}
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Update-gist
      run:  go run ./cmd/box/main.go
